include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_calls: true
    document_ignores: true
    package_api_docs: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_null_aware_spread: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    sort_child_properties_last: true
    unnecessary_new: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unused_import: true
    unused_label: true
    unused_shown_name: true
    use_rethrow_when_possible: true
    use_string_buffers: true
    use_super_parameters: true
